Accordion
js-tasks-ru/htmlcss-20230124_lialia-ru pull request #4
Opened 2023-02-02 20:25 UTC by lialia-ru

Сделала, вроде похоже, но стрелочки не стало после добавления summary display: block.

2023-02-02 20:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-03 10:23 UTC, GSemikozov requested changes

2023-02-03 10:23 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +body {
глобальные стили в файле стилей блока никогда не описываем, + все они относятся к аккордиону, нужно перенести в класс .accordion

2023-02-03 10:23 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 730px;
лишнее ограничение

2023-02-03 10:23 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item {
и еще при открытом .accordion__item[open] у accordion__content будет отступ сверху

2023-02-03 10:23 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item {
и другой паддинг снизу у .accordion__item[open]

2023-02-03 10:23 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                    <p class="accordion__content">
через <p> не нужно, контентом может быть все что угодно, поэтому - просто div

2023-02-04 14:55 UTC, lialia-ru commented on 03-lection1/02-accordion/accordion.css
> +body {
Перенесла

2023-02-04 14:57 UTC, lialia-ru commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 730px;
Убрала

2023-02-04 15:02 UTC, lialia-ru commented on 03-lection1/02-accordion/index.html
> +                    <p class="accordion__content">
Поменяла

2023-02-04 15:49 UTC, lialia-ru commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item {
Добавила про открытие

2023-02-04 15:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-06 09:51 UTC, GSemikozov approved these changes

2023-02-06 09:51 UTC, merged